#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
embed_webui.py — turn container/astro/webui/ into a C header the server can
serve straight out of .rodata.

    python3 embed_webui.py webui/ webui.h

WHY EMBED AT ALL
    The device has an SD card, so files would fit. But the web UI has to work
    when the card is absent, half-installed, or mounted read-only after an
    unclean power-off -- all three have happened on this hardware -- and a
    control panel that vanishes with its assets is worse than no control panel.
    One binary with no runtime dependencies cannot lose half of itself.

WHY GZIP AT BUILD TIME
    The Polaris' AP is 2.4 GHz and shares its single radio with everything else
    (see polaris-autojoin.sh). Shipping ~4x fewer bytes is the difference
    between a UI that appears and one that crawls. Compressing once at build
    time costs nothing at runtime -- the server just adds Content-Encoding.
    Every browser that can run the app supports gzip; there is no fallback path
    and none is needed.

WHY NO MINIFIER
    A hand-rolled minifier that mangles a template literal or eats a line in a
    regex produces a UI that fails in the browser with no build error. gzip
    already collapses the whitespace this would remove, so the trade is
    "identical bytes on the wire, unreadable source" -- a bad trade in a repo
    whose value is being able to see why something is the way it is.

Python 3.5 compatible ON PURPOSE: the build container is debian:9 (see
docker/Dockerfile, pinned for the device's glibc 2.24), whose python3 is 3.5.
No f-strings.
"""
import gzip
import os
import sys

# Only these extensions are embedded. An unknown file in webui/ is a mistake
# worth failing on rather than silently shipping (or silently dropping).
MIME = {
    ".html": "text/html; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".svg":  "image/svg+xml",
    ".json": "application/json",
    ".ico":  "image/x-icon",
    ".png":  "image/png",
    ".webp": "image/webp",
}
# Already-compressed formats: gzipping them wastes build time and can grow the
# file. Embedded raw, served without Content-Encoding.
NO_GZIP = {".png", ".ico", ".webp"}


def c_array(data):
    """Bytes -> C initialiser text, 16 per line, as unsigned hex."""
    out = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    " + ", ".join("0x%02x" % b for b in bytearray(chunk)) + ",")
    return "\n".join(out)


def ident(rel):
    """webui/app.js -> asset_app_js"""
    s = "asset_" + rel
    return "".join(ch if ch.isalnum() else "_" for ch in s)


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: embed_webui.py <srcdir> <out.h>\n")
        return 2
    srcdir, outpath = sys.argv[1], sys.argv[2]

    files = []
    for root, dirs, names in os.walk(srcdir):
        dirs.sort()
        for n in sorted(names):
            if n.startswith("."):
                continue
            full = os.path.join(root, n)
            rel = os.path.relpath(full, srcdir).replace(os.sep, "/")
            ext = os.path.splitext(n)[1].lower()
            if ext not in MIME:
                sys.stderr.write("embed_webui: refusing unknown asset type: %s\n" % rel)
                return 1
            files.append((rel, full, ext))

    if not files:
        sys.stderr.write("embed_webui: %s has no assets\n" % srcdir)
        return 1
    if not any(rel == "index.html" for rel, _, _ in files):
        sys.stderr.write("embed_webui: %s has no index.html\n" % srcdir)
        return 1

    chunks = []
    table = []
    total_raw = total_out = 0

    for rel, full, ext in files:
        with open(full, "rb") as fh:
            raw = fh.read()
        if ext in NO_GZIP:
            body, enc = raw, 0
        else:
            # mtime=0 so the output is byte-reproducible: a rebuild that
            # changes nothing should produce an identical header, or every
            # build looks like a diff.
            buf = __import__("io").BytesIO()
            gz = gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0)
            gz.write(raw)
            gz.close()
            body, enc = buf.getvalue(), 1
            if len(body) >= len(raw):      # tiny files can grow
                body, enc = raw, 0
        name = ident(rel)
        chunks.append("static const unsigned char %s[] = {\n%s\n};\n"
                      % (name, c_array(body)))
        table.append('    { "/%s", %s, sizeof %s, "%s", %d },'
                     % (rel, name, name, MIME[ext], enc))
        total_raw += len(raw)
        total_out += len(body)

    with open(outpath, "w") as out:
        out.write("/* GENERATED by embed_webui.py from %s -- do not edit.\n"
                  " * %d asset(s), %d bytes raw, %d bytes embedded (%.0f%%).\n */\n"
                  % (srcdir, len(files), total_raw, total_out,
                     100.0 * total_out / max(1, total_raw)))
        out.write("#ifndef POLARIS_WEBUI_H\n#define POLARIS_WEBUI_H\n\n")
        out.write("#include <stddef.h>\n\n")
        out.write("\n".join(chunks))
        out.write("\ntypedef struct {\n"
                  "    const char          *path;   /* request path, leading slash   */\n"
                  "    const unsigned char *body;\n"
                  "    size_t               len;\n"
                  "    const char          *ctype;\n"
                  "    int                  gzip;   /* 1 => send Content-Encoding    */\n"
                  "} webui_asset_t;\n\n")
        out.write("static const webui_asset_t WEBUI_ASSETS[] = {\n")
        out.write("\n".join(table))
        out.write("\n};\n")
        out.write("#define WEBUI_ASSET_COUNT (sizeof WEBUI_ASSETS / sizeof WEBUI_ASSETS[0])\n\n")
        out.write("#endif /* POLARIS_WEBUI_H */\n")

    sys.stderr.write("embed_webui: %d asset(s), %d -> %d bytes (%.0f%%) -> %s\n"
                     % (len(files), total_raw, total_out,
                        100.0 * total_out / max(1, total_raw), outpath))
    return 0


if __name__ == "__main__":
    sys.exit(main())
