#!/bin/sh
# ===========================================================================
#  setup-wifi.sh -- write wpa.conf for the station interface, interactively,
#  ON THE DEVICE.
#
#  The password is typed at your terminal, travels over your ssh session, and
#  is turned into a PSK hash here. It is never passed as a command-line
#  argument (which would show in `ps`), never echoed back, and the plaintext
#  copy that wpa_passphrase helpfully writes into its own output as a comment
#  is stripped before the file is saved.
#
#  What lands on the card is the hashed PSK. That hash is still enough to join
#  the network, so the file is chmod 600 -- treat it as a credential.
# ===========================================================================
WDIR=${WIFI_DIR:-/app/sd/polaris-wifi}
CONF="$WDIR/wpa.conf"

[ -x "$WDIR/wpa_passphrase" ] || { echo "missing $WDIR/wpa_passphrase" >&2; exit 2; }

printf 'Wi-Fi network name (SSID): '
read SSID
[ -n "$SSID" ] || { echo "no SSID given" >&2; exit 1; }

# stty -echo so the password is not shown as it is typed
stty -echo 2>/dev/null
printf 'Password (not shown): '
read PSK
stty echo 2>/dev/null
printf '\n'
[ -n "$PSK" ] || { echo "no password given" >&2; exit 1; }

TMP="$WDIR/.wpa.tmp"
{
    echo "ctrl_interface=/var/run/wpa_supplicant"
    echo "update_config=1"
    echo "# generated by setup-wifi.sh -- contains a PSK hash; keep it private"
} > "$TMP"

# wpa_passphrase writes the plaintext back as a #psk="..." comment. Drop it.
"$WDIR/wpa_passphrase" "$SSID" "$PSK" 2>/dev/null | grep -v '^[[:space:]]*#psk=' >> "$TMP" \
    || { rm -f "$TMP"; echo "wpa_passphrase failed (password shorter than 8 characters?)" >&2; exit 3; }
PSK=""

mv "$TMP" "$CONF"
chmod 600 "$CONF"

echo
echo "wrote $CONF"
echo "  ssid:  $(sed -n 's/^[[:space:]]*ssid=\(.*\)/\1/p' "$CONF")"
echo "  psk:   $(sed -n 's/^[[:space:]]*psk=\(....\).*/\1…(hashed)/p' "$CONF")"
echo "  plaintext password present in the file: $(grep -c '#psk=' "$CONF") (must be 0)"
echo
echo "now run:  $WDIR/polaris-apsta.sh up"
